// src/Components/MealCategoryManagementModal.js
import React, { useState, useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import './MealCategoryManagementModal.css';

const MealCategoryManagementModal = observer(({ isOpen, onClose, mealPlanViewModel }) => {
    const [newCategoryName, setNewCategoryName] = useState('');
    const [newCategoryDescription, setNewCategoryDescription] = useState('');

    const [editingCategory, setEditingCategory] = useState(null); // Stores the category being edited
    const [editCategoryName, setEditCategoryName] = useState('');
    const [editCategoryDescription, setEditCategoryDescription] = useState('');

    const [modalLoading, setModalLoading] = useState(false);
    const [modalError, setModalError] = useState('');

    // Fetch categories when modal opens
    useEffect(() => {
        if (isOpen) {
            mealPlanViewModel.fetchMealCategories();
            setModalError('');
            // Reset new category form
            setNewCategoryName('');
            setNewCategoryDescription('');
            // Reset editing state
            setEditingCategory(null);
            setEditCategoryName('');
            setEditCategoryDescription('');
        }
    }, [isOpen, mealPlanViewModel]);

    const handleCreateCategory = async (e) => {
        e.preventDefault();
        setModalLoading(true);
        setModalError('');
        try {
            await mealPlanViewModel.createMealCategory({
                categoryName: newCategoryName,
                categoryDescription: newCategoryDescription,
                // categoryId will now be auto-generated by the service
            });
            setNewCategoryName('');
            setNewCategoryDescription('');
        } catch (error) {
            setModalError('Failed to add category: ' + error.message);
        } finally {
            setModalLoading(false);
        }
    };

    const handleEditClick = (category) => {
        setEditingCategory(category);
        setEditCategoryName(category.categoryName);
        setEditCategoryDescription(category.categoryDescription);
        setModalError('');
    };

    const handleUpdateCategory = async (e) => {
        e.preventDefault();
        if (!editingCategory) return;

        setModalLoading(true);
        setModalError('');
        try {
            await mealPlanViewModel.updateMealCategory(editingCategory.id, {
                categoryName: editCategoryName,
                categoryDescription: editCategoryDescription,
                // categoryId will not be updated via the modal anymore
            });
            setEditingCategory(null); // Exit edit mode
            setEditCategoryName('');
            setEditCategoryDescription('');
        } catch (error) {
            setModalError('Failed to update category: ' + error.message);
        } finally {
            setModalLoading(false);
        }
    };

    const handleDeleteCategory = async (id) => {
        if (window.confirm('Are you sure you want to delete this category? This cannot be undone.')) {
            setModalLoading(true);
            setModalError('');
            try {
                await mealPlanViewModel.deleteMealCategory(id);
            } catch (error) {
                setModalError('Failed to delete category: ' + error.message);
            } finally {
                setModalLoading(false);
            }
        }
    };

    if (!isOpen) return null;

    return (
        <div className="meal-category-modal-overlay">
            <div className="meal-category-modal-content">
                <h2 className="meal-category-modal-title">Manage Meal Plan Categories</h2>
                {modalLoading && <p className="meal-category-loading-text">Loading...</p>}
                {modalError && <p className="meal-category-error-message">{modalError}</p>}

                {/* Create New Category Form */}
                <div className="meal-category-create-section">
                    <h3 className="meal-category-section-title">Create New Category</h3>
                    <form onSubmit={handleCreateCategory}>
                        <div className="meal-category-form-group">
                            <label htmlFor="newCategoryName" className="meal-category-form-label">Category Name:</label>
                            <input
                                type="text"
                                id="newCategoryName"
                                className="meal-category-form-input"
                                value={newCategoryName}
                                onChange={(e) => setNewCategoryName(e.target.value)}
                                required
                                placeholder="Enter category name..."
                            />
                        </div>
                        <div className="meal-category-form-group">
                            <label htmlFor="newCategoryDescription" className="meal-category-form-label">Description:</label>
                            <textarea
                                id="newCategoryDescription"
                                className="meal-category-form-textarea"
                                value={newCategoryDescription}
                                onChange={(e) => setNewCategoryDescription(e.target.value)}
                                rows="3"
                                required
                                placeholder="Enter category description..."
                            ></textarea>
                        </div>
                        <button 
                            type="submit" 
                            className="meal-category-button meal-category-create-button" 
                            disabled={modalLoading}
                        >
                            Add Category
                        </button>
                    </form>
                </div>

                {/* Existing Categories List */}
                <div className="meal-category-existing-section">
                    <h3 className="meal-category-section-title">Existing Categories</h3>
                    {mealPlanViewModel.loadingCategories ? (
                        <p className="meal-category-loading-text">Loading categories...</p>
                    ) : (
                        <ul className="meal-category-list">
                            {mealPlanViewModel.allCategoriesWithDetails.length === 0 ? (
                                <p className="meal-category-no-items">No categories found.</p>
                            ) : (
                                mealPlanViewModel.allCategoriesWithDetails.map(category => (
                                    <li key={category.id} className="meal-category-item">
                                        {editingCategory?.id === category.id ? (
                                            <form onSubmit={handleUpdateCategory} className="meal-category-edit-form">
                                                <div className="meal-category-form-group">
                                                    <label htmlFor={`editName-${category.id}`} className="meal-category-form-label">Name:</label>
                                                    <input
                                                        type="text"
                                                        id={`editName-${category.id}`}
                                                        className="meal-category-form-input"
                                                        value={editCategoryName}
                                                        onChange={(e) => setEditCategoryName(e.target.value)}
                                                        required
                                                    />
                                                </div>
                                                <div className="meal-category-form-group">
                                                    <label htmlFor={`editDesc-${category.id}`} className="meal-category-form-label">Description:</label>
                                                    <textarea
                                                        id={`editDesc-${category.id}`}
                                                        className="meal-category-form-textarea"
                                                        value={editCategoryDescription}
                                                        onChange={(e) => setEditCategoryDescription(e.target.value)}
                                                        rows="2"
                                                        required
                                                    ></textarea>
                                                </div>
                                                <div className="meal-category-edit-actions">
                                                    <button 
                                                        type="submit" 
                                                        className="meal-category-button meal-category-update-button" 
                                                        disabled={modalLoading}
                                                    >
                                                        Update
                                                    </button>
                                                    <button 
                                                        type="button" 
                                                        onClick={() => setEditingCategory(null)} 
                                                        className="meal-category-button meal-category-cancel-button"
                                                        disabled={modalLoading}
                                                    >
                                                        Cancel
                                                    </button>
                                                </div>
                                            </form>
                                        ) : (
                                            <>
                                                <div className="meal-category-item-content">
                                                    <h4 className="meal-category-item-name">{category.categoryName}</h4>
                                                    <p className="meal-category-item-description">{category.categoryDescription}</p>
                                                </div>
                                                <div className="meal-category-item-actions">
                                                    <button 
                                                        onClick={() => handleEditClick(category)} 
                                                        disabled={modalLoading}
                                                        className="meal-category-button meal-category-edit-button"
                                                    >
                                                        Edit
                                                    </button>
                                                    <button 
                                                        onClick={() => handleDeleteCategory(category.id)} 
                                                        disabled={modalLoading} 
                                                        className="meal-category-button meal-category-delete-button"
                                                    >
                                                        Delete
                                                    </button>
                                                </div>
                                            </>
                                        )}
                                    </li>
                                ))
                            )}
                        </ul>
                    )}
                </div>

                {/* Modal Actions */}
                <div className="meal-category-modal-actions">
                    <button 
                        className="meal-category-button meal-category-close-button" 
                        onClick={onClose} 
                        disabled={modalLoading}
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
});

export default MealCategoryManagementModal;